import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { Roboto_Condensed } from 'next/font/google'
import './globals.css'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})
const robotoCondensed = Roboto_Condensed({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
  variable: '--font-roboto-condensed',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br" className="items-center flex">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${robotoCondensed.className} antialiased w-full max-w-[1280px] pl-6 pr-6 bg-blue-700 flex flex-col justify-center`}
      >
        {children}
      </body>
    </html>
  )
}
